baseURL: 'http://prafullchvn.github.io'
languageCode: en-us
title: Welcome to Prafull's blog
theme: paperMod
params:
  comments: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  profileMode:
    enabled: true
    title: "Prafull's blog" # optional default will be site title
    subtitle: 'Read about tech and life on my blog'
    imageUrl: 'https://avatars.githubusercontent.com/u/99485204?v=4' # optional
    imageTitle: 'My Image' # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      # - name: Archive
      #   url: '/archive'
      - name: Github
        url: 'https://github.com/prafullchvn'

  socialIcons: # optional
    - name: 'Twitter'
      url: 'https://twitter.com/_leg_pc'
    # - name: '<platform 2>'
    #   url: '<link2>'
languages:
  en:
    languageName: 'English'
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Posts
          url: /posts
disqusShortname: prafullchvn-github-io-1
